services:
  postgres:
    image: postgres:16
    container_name: lan_traffic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lan_traffic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
      - ./sql/002_seed.sql:/docker-entrypoint-initdb.d/002_seed.sql:ro
      - ./sql/003_db_objects.sql:/docker-entrypoint-initdb.d/003_db_objects.sql:ro

volumes:
  postgres_data:
